# coding: utf-8

"""
    Powerbot Server

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from powerbot.models.signal import Signal  # noqa: F401,E501


class Contract(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'product': 'str',
        'contract_id': 'int',
        'name': 'str',
        'revision_no': 'int',
        'delivery_start': 'datetime',
        'delivery_end': 'datetime',
        'best_bid_price': 'float',
        'best_bid_quantity': 'float',
        'best_ask_price': 'float',
        'best_ask_quantity': 'float',
        'last_price': 'float',
        'last_quantity': 'float',
        'total_quantity': 'float',
        'auction_price': 'float',
        'high': 'float',
        'low': 'float',
        'contract_details': 'object',
        'orderbook_details': 'object',
        'relative_position': 'float',
        'absolute_position': 'float',
        'last_trade_time': 'datetime',
        'signals': 'list[Signal]'
    }

    attribute_map = {
        'product': 'product',
        'contract_id': 'contract_id',
        'name': 'name',
        'revision_no': 'revision_no',
        'delivery_start': 'delivery_start',
        'delivery_end': 'delivery_end',
        'best_bid_price': 'best_bid_price',
        'best_bid_quantity': 'best_bid_quantity',
        'best_ask_price': 'best_ask_price',
        'best_ask_quantity': 'best_ask_quantity',
        'last_price': 'last_price',
        'last_quantity': 'last_quantity',
        'total_quantity': 'total_quantity',
        'auction_price': 'auction_price',
        'high': 'high',
        'low': 'low',
        'contract_details': 'contract_details',
        'orderbook_details': 'orderbook_details',
        'relative_position': 'relative_position',
        'absolute_position': 'absolute_position',
        'last_trade_time': 'last_trade_time',
        'signals': 'signals'
    }

    def __init__(self, product=None, contract_id=None, name=None, revision_no=None, delivery_start=None, delivery_end=None, best_bid_price=None, best_bid_quantity=None, best_ask_price=None, best_ask_quantity=None, last_price=None, last_quantity=None, total_quantity=None, auction_price=None, high=None, low=None, contract_details=None, orderbook_details=None, relative_position=None, absolute_position=None, last_trade_time=None, signals=None):  # noqa: E501
        """Contract - a model defined in Swagger"""  # noqa: E501

        self._product = None
        self._contract_id = None
        self._name = None
        self._revision_no = None
        self._delivery_start = None
        self._delivery_end = None
        self._best_bid_price = None
        self._best_bid_quantity = None
        self._best_ask_price = None
        self._best_ask_quantity = None
        self._last_price = None
        self._last_quantity = None
        self._total_quantity = None
        self._auction_price = None
        self._high = None
        self._low = None
        self._contract_details = None
        self._orderbook_details = None
        self._relative_position = None
        self._absolute_position = None
        self._last_trade_time = None
        self._signals = None
        self.discriminator = None

        if product is not None:
            self.product = product
        if contract_id is not None:
            self.contract_id = contract_id
        if name is not None:
            self.name = name
        if revision_no is not None:
            self.revision_no = revision_no
        if delivery_start is not None:
            self.delivery_start = delivery_start
        if delivery_end is not None:
            self.delivery_end = delivery_end
        if best_bid_price is not None:
            self.best_bid_price = best_bid_price
        if best_bid_quantity is not None:
            self.best_bid_quantity = best_bid_quantity
        if best_ask_price is not None:
            self.best_ask_price = best_ask_price
        if best_ask_quantity is not None:
            self.best_ask_quantity = best_ask_quantity
        if last_price is not None:
            self.last_price = last_price
        if last_quantity is not None:
            self.last_quantity = last_quantity
        if total_quantity is not None:
            self.total_quantity = total_quantity
        if auction_price is not None:
            self.auction_price = auction_price
        if high is not None:
            self.high = high
        if low is not None:
            self.low = low
        if contract_details is not None:
            self.contract_details = contract_details
        if orderbook_details is not None:
            self.orderbook_details = orderbook_details
        if relative_position is not None:
            self.relative_position = relative_position
        if absolute_position is not None:
            self.absolute_position = absolute_position
        if last_trade_time is not None:
            self.last_trade_time = last_trade_time
        if signals is not None:
            self.signals = signals

    @property
    def product(self):
        """Gets the product of this Contract.  # noqa: E501


        :return: The product of this Contract.  # noqa: E501
        :rtype: str
        """
        return self._product

    @product.setter
    def product(self, product):
        """Sets the product of this Contract.


        :param product: The product of this Contract.  # noqa: E501
        :type: str
        """

        self._product = product

    @property
    def contract_id(self):
        """Gets the contract_id of this Contract.  # noqa: E501


        :return: The contract_id of this Contract.  # noqa: E501
        :rtype: int
        """
        return self._contract_id

    @contract_id.setter
    def contract_id(self, contract_id):
        """Sets the contract_id of this Contract.


        :param contract_id: The contract_id of this Contract.  # noqa: E501
        :type: int
        """

        self._contract_id = contract_id

    @property
    def name(self):
        """Gets the name of this Contract.  # noqa: E501


        :return: The name of this Contract.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Contract.


        :param name: The name of this Contract.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def revision_no(self):
        """Gets the revision_no of this Contract.  # noqa: E501


        :return: The revision_no of this Contract.  # noqa: E501
        :rtype: int
        """
        return self._revision_no

    @revision_no.setter
    def revision_no(self, revision_no):
        """Sets the revision_no of this Contract.


        :param revision_no: The revision_no of this Contract.  # noqa: E501
        :type: int
        """

        self._revision_no = revision_no

    @property
    def delivery_start(self):
        """Gets the delivery_start of this Contract.  # noqa: E501


        :return: The delivery_start of this Contract.  # noqa: E501
        :rtype: datetime
        """
        return self._delivery_start

    @delivery_start.setter
    def delivery_start(self, delivery_start):
        """Sets the delivery_start of this Contract.


        :param delivery_start: The delivery_start of this Contract.  # noqa: E501
        :type: datetime
        """

        self._delivery_start = delivery_start

    @property
    def delivery_end(self):
        """Gets the delivery_end of this Contract.  # noqa: E501


        :return: The delivery_end of this Contract.  # noqa: E501
        :rtype: datetime
        """
        return self._delivery_end

    @delivery_end.setter
    def delivery_end(self, delivery_end):
        """Sets the delivery_end of this Contract.


        :param delivery_end: The delivery_end of this Contract.  # noqa: E501
        :type: datetime
        """

        self._delivery_end = delivery_end

    @property
    def best_bid_price(self):
        """Gets the best_bid_price of this Contract.  # noqa: E501


        :return: The best_bid_price of this Contract.  # noqa: E501
        :rtype: float
        """
        return self._best_bid_price

    @best_bid_price.setter
    def best_bid_price(self, best_bid_price):
        """Sets the best_bid_price of this Contract.


        :param best_bid_price: The best_bid_price of this Contract.  # noqa: E501
        :type: float
        """

        self._best_bid_price = best_bid_price

    @property
    def best_bid_quantity(self):
        """Gets the best_bid_quantity of this Contract.  # noqa: E501


        :return: The best_bid_quantity of this Contract.  # noqa: E501
        :rtype: float
        """
        return self._best_bid_quantity

    @best_bid_quantity.setter
    def best_bid_quantity(self, best_bid_quantity):
        """Sets the best_bid_quantity of this Contract.


        :param best_bid_quantity: The best_bid_quantity of this Contract.  # noqa: E501
        :type: float
        """

        self._best_bid_quantity = best_bid_quantity

    @property
    def best_ask_price(self):
        """Gets the best_ask_price of this Contract.  # noqa: E501


        :return: The best_ask_price of this Contract.  # noqa: E501
        :rtype: float
        """
        return self._best_ask_price

    @best_ask_price.setter
    def best_ask_price(self, best_ask_price):
        """Sets the best_ask_price of this Contract.


        :param best_ask_price: The best_ask_price of this Contract.  # noqa: E501
        :type: float
        """

        self._best_ask_price = best_ask_price

    @property
    def best_ask_quantity(self):
        """Gets the best_ask_quantity of this Contract.  # noqa: E501


        :return: The best_ask_quantity of this Contract.  # noqa: E501
        :rtype: float
        """
        return self._best_ask_quantity

    @best_ask_quantity.setter
    def best_ask_quantity(self, best_ask_quantity):
        """Sets the best_ask_quantity of this Contract.


        :param best_ask_quantity: The best_ask_quantity of this Contract.  # noqa: E501
        :type: float
        """

        self._best_ask_quantity = best_ask_quantity

    @property
    def last_price(self):
        """Gets the last_price of this Contract.  # noqa: E501


        :return: The last_price of this Contract.  # noqa: E501
        :rtype: float
        """
        return self._last_price

    @last_price.setter
    def last_price(self, last_price):
        """Sets the last_price of this Contract.


        :param last_price: The last_price of this Contract.  # noqa: E501
        :type: float
        """

        self._last_price = last_price

    @property
    def last_quantity(self):
        """Gets the last_quantity of this Contract.  # noqa: E501


        :return: The last_quantity of this Contract.  # noqa: E501
        :rtype: float
        """
        return self._last_quantity

    @last_quantity.setter
    def last_quantity(self, last_quantity):
        """Sets the last_quantity of this Contract.


        :param last_quantity: The last_quantity of this Contract.  # noqa: E501
        :type: float
        """

        self._last_quantity = last_quantity

    @property
    def total_quantity(self):
        """Gets the total_quantity of this Contract.  # noqa: E501


        :return: The total_quantity of this Contract.  # noqa: E501
        :rtype: float
        """
        return self._total_quantity

    @total_quantity.setter
    def total_quantity(self, total_quantity):
        """Sets the total_quantity of this Contract.


        :param total_quantity: The total_quantity of this Contract.  # noqa: E501
        :type: float
        """

        self._total_quantity = total_quantity

    @property
    def auction_price(self):
        """Gets the auction_price of this Contract.  # noqa: E501


        :return: The auction_price of this Contract.  # noqa: E501
        :rtype: float
        """
        return self._auction_price

    @auction_price.setter
    def auction_price(self, auction_price):
        """Sets the auction_price of this Contract.


        :param auction_price: The auction_price of this Contract.  # noqa: E501
        :type: float
        """

        self._auction_price = auction_price

    @property
    def high(self):
        """Gets the high of this Contract.  # noqa: E501


        :return: The high of this Contract.  # noqa: E501
        :rtype: float
        """
        return self._high

    @high.setter
    def high(self, high):
        """Sets the high of this Contract.


        :param high: The high of this Contract.  # noqa: E501
        :type: float
        """

        self._high = high

    @property
    def low(self):
        """Gets the low of this Contract.  # noqa: E501


        :return: The low of this Contract.  # noqa: E501
        :rtype: float
        """
        return self._low

    @low.setter
    def low(self, low):
        """Sets the low of this Contract.


        :param low: The low of this Contract.  # noqa: E501
        :type: float
        """

        self._low = low

    @property
    def contract_details(self):
        """Gets the contract_details of this Contract.  # noqa: E501


        :return: The contract_details of this Contract.  # noqa: E501
        :rtype: object
        """
        return self._contract_details

    @contract_details.setter
    def contract_details(self, contract_details):
        """Sets the contract_details of this Contract.


        :param contract_details: The contract_details of this Contract.  # noqa: E501
        :type: object
        """

        self._contract_details = contract_details

    @property
    def orderbook_details(self):
        """Gets the orderbook_details of this Contract.  # noqa: E501


        :return: The orderbook_details of this Contract.  # noqa: E501
        :rtype: object
        """
        return self._orderbook_details

    @orderbook_details.setter
    def orderbook_details(self, orderbook_details):
        """Sets the orderbook_details of this Contract.


        :param orderbook_details: The orderbook_details of this Contract.  # noqa: E501
        :type: object
        """

        self._orderbook_details = orderbook_details

    @property
    def relative_position(self):
        """Gets the relative_position of this Contract.  # noqa: E501


        :return: The relative_position of this Contract.  # noqa: E501
        :rtype: float
        """
        return self._relative_position

    @relative_position.setter
    def relative_position(self, relative_position):
        """Sets the relative_position of this Contract.


        :param relative_position: The relative_position of this Contract.  # noqa: E501
        :type: float
        """

        self._relative_position = relative_position

    @property
    def absolute_position(self):
        """Gets the absolute_position of this Contract.  # noqa: E501


        :return: The absolute_position of this Contract.  # noqa: E501
        :rtype: float
        """
        return self._absolute_position

    @absolute_position.setter
    def absolute_position(self, absolute_position):
        """Sets the absolute_position of this Contract.


        :param absolute_position: The absolute_position of this Contract.  # noqa: E501
        :type: float
        """

        self._absolute_position = absolute_position

    @property
    def last_trade_time(self):
        """Gets the last_trade_time of this Contract.  # noqa: E501


        :return: The last_trade_time of this Contract.  # noqa: E501
        :rtype: datetime
        """
        return self._last_trade_time

    @last_trade_time.setter
    def last_trade_time(self, last_trade_time):
        """Sets the last_trade_time of this Contract.


        :param last_trade_time: The last_trade_time of this Contract.  # noqa: E501
        :type: datetime
        """

        self._last_trade_time = last_trade_time

    @property
    def signals(self):
        """Gets the signals of this Contract.  # noqa: E501


        :return: The signals of this Contract.  # noqa: E501
        :rtype: list[Signal]
        """
        return self._signals

    @signals.setter
    def signals(self, signals):
        """Sets the signals of this Contract.


        :param signals: The signals of this Contract.  # noqa: E501
        :type: list[Signal]
        """

        self._signals = signals

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Contract):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
