# coding: utf-8

"""
    Powerbot Server

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from powerbot.models.order_book_entry import OrderBookEntry  # noqa: F401,E501


class Orders(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bid': 'list[OrderBookEntry]',
        'ask': 'list[OrderBookEntry]'
    }

    attribute_map = {
        'bid': 'bid',
        'ask': 'ask'
    }

    def __init__(self, bid=None, ask=None):  # noqa: E501
        """Orders - a model defined in Swagger"""  # noqa: E501

        self._bid = None
        self._ask = None
        self.discriminator = None

        if bid is not None:
            self.bid = bid
        if ask is not None:
            self.ask = ask

    @property
    def bid(self):
        """Gets the bid of this Orders.  # noqa: E501


        :return: The bid of this Orders.  # noqa: E501
        :rtype: list[OrderBookEntry]
        """
        return self._bid

    @bid.setter
    def bid(self, bid):
        """Sets the bid of this Orders.


        :param bid: The bid of this Orders.  # noqa: E501
        :type: list[OrderBookEntry]
        """

        self._bid = bid

    @property
    def ask(self):
        """Gets the ask of this Orders.  # noqa: E501


        :return: The ask of this Orders.  # noqa: E501
        :rtype: list[OrderBookEntry]
        """
        return self._ask

    @ask.setter
    def ask(self, ask):
        """Sets the ask of this Orders.


        :param ask: The ask of this Orders.  # noqa: E501
        :type: list[OrderBookEntry]
        """

        self._ask = ask

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Orders):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
